### ISSUE TITLE
Found a little bug

### ISSUE THREAD

**Issue by nietoperz809** [EgonOlsen71/basicv2#1]
Endless loops are unstoppable, e.g. `10 goto 10`
Insert at the top of the for loop (Interpreter, line 495) the following code: `if (stop) return;`
Then it will break if someone calls runStop()

👍

**Comment by EgonOlsen71** [comment]
Fixed it. However, you are using an outdated version anyway. The Interpreter class is long gone and has been remaned to Basic.
