### ISSUE TITLE
Why tests are programs?

### ISSUE THREAD

**Issue by kdrzazga** [EgonOlsen71/basicv2#16]
I believe JUnit or similar should be used.

**Comment by EgonOlsen71** [comment]
Two reasons: They aren't really automated tests of the Junit kind, i.e. in a lot of cases, you have to look at the outcome to tell if it's correct or not. You can't Junit-test a compiled game for example.
Apart from that, I wanted this project to have no third party libs at all, hence no junit here.

**Comment by kdrzazga** [comment]
I could ask why you use Java instead of wiriting your own VM? LOL 
Anyway, to JUnit-test a compiled game logging can be used.

**Comment by EgonOlsen71** [comment]
No, it can't. Junit doesn't run an a C64...
