### ISSUE TITLE
optimize real variable assignment from constant

### ISSUE THREAD

**Issue by nippur72** [EgonOlsen71/basicv2#20]
The statement `B=5` is rendered as (opts=true):
```
LDA #<CONST_0R
LDY #>CONST_0R
JSR REALFAC
LDX #<VAR_B
LDY #>VAR_B
JSR FACMEM
```
that is: load constant into FAC and then from FAC to var B (if my understanding is right)

I think that could be optimized with the equivalent:
```
ldx #4
loop:
  lda CONST_0R, x
  sta VAR_B, x
  dex
  bpl loop
```
which is faster and also shorter (11 vs 14 bytes). The only downside would be the use of the `X` register.

**Comment by EgonOlsen71** [comment]
Seems reasonable. But it's pretty obvious, so I wonder why I don't do it already. Maybe there's a catch like the value actually needed in the FAC in some cases or something like that. I'll look into it...

**Comment by EgonOlsen71** [comment]
I've added the optimization as suggested. I don't see any negative side effects of it, so all is well. It doesn't really help much performance wise though. In my fractal test case, it improved performance by 0.1% but it also shaved off a few bytes so there's no reason not to apply it.

**Comment by nippur72** [comment]
great thanks!
