### ISSUE TITLE
inline .WORD constants

### ISSUE THREAD

**Issue by nippur72** [EgonOlsen71/basicv2#24]
Integer constants are created as `.WORD` but I guess they can be inlined directly using the 6502 immediate mode (`#`), saving the bytes and making it a little faster.

E.g. the statement `K%=32`:
```
; current
LDY CONST_6
LDA CONST_6+1
; Optimizer rule: INT to FAC, FAC to INT/2
STY VAR_K%
STA VAR_K%+1
```
```
; suggested
LDY #32
LDA #0
; Optimizer rule: INT to FAC, FAC to INT/2
STY VAR_K%
STA VAR_K%+1
```

**Comment by EgonOlsen71** [comment]
That's a nice idea, adding it was quite straight forward. However, while being there, I encountered another problem in the initialization of string arrays that was harder to track down. Should be fixed now as well. I also reformatted the whole code, because it was somehow broken for me.
