### ISSUE TITLE
How to use from any directory and avoid "Error: Could not find or load main class com.sixtyfour.cbmnative.shell.MoSpeedCL"

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [EgonOlsen71/basicv2#33]
If I run it outside the dist directory I get: "Error: Could not find or load main class com.sixtyfour.cbmnative.shell.MoSpeedCL"

Is there a suggested clean way to install the compiler in a way that it can be called from anywhere?

**Comment by nippur72** [comment]
same issue here. 

I suspect a regression because an older version of the `.jar` is working fine as usual.

**Comment by EgonOlsen71** [comment]
That's strange. I haven't changed anything on purpose, not the cmd and not the jar in that respect. I would try for myself, but I'm on holiday at the moment, so I can't.

**Comment by EgonOlsen71** [comment]
I don't see how this could have ever worked this way. The java searches for the jar in the current directory and in a subdir called "dist" of the current directory. Neither can be found if you call it from somewhere else by adding the cmd's directory to the PATH.
I've updated the cmd-file now, so that it searches in the PATHed-to directory as well. I worked for me, please give it a try.

**Comment by nippur72** [comment]
I've just tried it on my W10 machine and it works perfectly, thanks!

**Comment by Lindwedler** [comment]
Hello, i have the same problem. I get alway an error message that the class MoSpeed could not be found. What can i do?

![error](https://user-images.githubusercontent.com/12213885/71599524-7729ef80-2b4b-11ea-9c9a-0b39e56f0e92.png)

**Comment by EgonOlsen71** [comment]
Looks like a problem with the space in the directory name. That seems to confuse Java somehow. Try to rename the directory to something without a space in it and try again.

**Comment by Lindwedler** [comment]
Yes, thats it! Now it works. Thank you very much!!!

**Comment by EgonOlsen71** [comment]
I'll look into why this happens. Might be something that I can fix in the script somehow.
