### ISSUE TITLE
Run on X16 enumerator r32

### ISSUE THREAD

**Issue by ObelixSoftware** [EgonOlsen71/basicv2#34]
I compile my BASIC program with the following command:

./mospeed.sh speed_test.bas /target=speed_test.prg /platform=x16 -generatesrc=true /addressheader=true

When I then open up the X16 enumerator r32:

 ./x16emu -echo -debug -run -prg peed_test.prg 

The screen just go blank but i don't see my output.

Maybe an error in the generated prg ?

**Comment by EgonOlsen71** [comment]
The compiler compiles against r33, it's not compatible with r32. You can either download the last r32 compatible release from the release page or use the r33 emulator instead, which is what I would recommend.

**Comment by EgonOlsen71** [comment]
Oops...I've just noticed that there is no r32 release on the releases page. I guess your only option is to use the r33 emulator then...

**Comment by lenniedv** [comment]
Tested and works with r33 emulator

**Comment by EgonOlsen71** [comment]
In theory, the compiler could compile for another ROM/emulator version by providing it with a different symbol table file (using the /symboltable=<file>flag). However, for now the changes between releases of the emulator are so drastic that this alone doesn't cut it, I'm afraid.
