### ISSUE TITLE
increase in size in the generated output with latest releases

### ISSUE THREAD

**Issue by nippur72** [EgonOlsen71/basicv2#36]
I just switched from an old version of the compiler (2018 circa pre X16) to the latest release and I noticed an increase in size in the generated output. What before was 12794 bytes is now 13650 (with the same command line arguments).

I wonder if it's because a change in `compactlevel` default value, or if it's something else.

**Comment by EgonOlsen71** [comment]
No, it's most likely caused by the additional floating point routines that the runtime now includes, which replace +,-,*,/ and SQR with faster ones. You can compile with /xfloatopt=false to disable them.

**Comment by nippur72** [comment]
thank you
