### ISSUE TITLE
MOSSpeed jar file

### ISSUE THREAD

**Issue by phaze101** [EgonOlsen71/basicv2#37]
Apologies but I am missing something. Where is the MOSSpeed jar file in the dist directory? I do not see it there.

**Comment by EgonOlsen71** [comment]
It's not called that way. It's called basicv2.jar, because the project initially was (and in parts still is) a reimplementation of Basic V2 in Java. The cross compiler to generate actual 6502 code is just one aspect of it.

**Comment by phaze101** [comment]
Thanks I figured it out in the end. I got confused because the Wiki states so. Anyway thanks once again.

**Comment by phaze101** [comment]
Closing this
