### ISSUE TITLE
BasicShell: no INPUT for numeric variable possible

### ISSUE THREAD

**Issue by viteisele** [EgonOlsen71/basicv2#50]
I opened a new issue#1 for project C64Screen:
When there is a INPUT for a numeric variable, e. g. 100 INPUT A, after pressing return there is always following error although the input was numeric, e. g. 1:
?REDO FROM START

This error is probably caused by BasicShell.

**Comment by EgonOlsen71** [comment]
There was a stray character at the start of each input string when using the shell. Should be fixed now.

**Comment by viteisele** [comment]
It works now, thank you :-)
