### ISSUE TITLE
Is PI supported ?

### ISSUE THREAD

**Issue by viteisele** [EgonOlsen71/basicv2#51]
I normally use text files as input for compiler/interpreter. 
But I have a problem when I want to use the character for PI (chr$(126) in Commodore Basic) as function (result 3.1415...), e. g. for print or as part of a calculation.
When I try the usual solution as "~", ALT-960 or ALT-227, then there is either a syntax error or zero is returned.

**Comment by EgonOlsen71** [comment]
You can use Π in text sources.

**Comment by viteisele** [comment]
With following line: 10 print Π
console prints 3.14159265, but the output of compiled code is still 0.

BTW: The console accepts both forms of PI:  the Greek Capital Letter Pi (Π, U+03A0, &Pi) and the Greek Small Letter Pi (π, U+03C0, &pi), which looks the PI in Commodore Basic.

**Comment by EgonOlsen71** [comment]
You are right...strange. I guess I've never tested it in this context, because I really dislike the idea of having an extra symbol for PI in the first place hence I never use it but write 3.1415...directly. I'll have a look. Most likely some kind of encoding conversion issue...

**Comment by EgonOlsen71** [comment]
Should be fixed now.

**Comment by viteisele** [comment]
The function PI is now working :-)
But there is one little difference between compiler and console when printing character PI (print "π") with text files:
with compiled code it is printed as expected, but with console the is something like "|PI|".
Could you also fix  this ?

**Comment by EgonOlsen71** [comment]
I'll have look. That should actually happen only inside strings...

**Comment by viteisele** [comment]
Here is the testprogram:
 0 print chr$(126)
1 print "Π"
2 print "π"

With compiler and emulator there are 3 π printed.
With console there is the output with bash (I use wsl):

./run_gui.sh
com.sixtyfour.extensions.textmode.ConsoleSupport registered as a BASIC extension!
com.sixtyfour.extensions.graphics.GraphicsBasic registered as a BASIC extension!
3 commands compiled in: 56ms
~
{pi}
{pi}

The output for line 20 and 30 in the gui is the same as for 'print "{pi}"' ,  line 10 has correct output.
Sorry, I don't know how to add a screenshot.

**Comment by EgonOlsen71** [comment]
I see. That's actually "by design"...which doesn't mean, that it's a good design. I'll have a look at it...

**Comment by EgonOlsen71** [comment]
Should behave better now...

**Comment by viteisele** [comment]
Yes, now compiler and console have the same correct behavior :-)
