### ISSUE TITLE
Loading PRG files works only with compiler

### ISSUE THREAD

**Issue by viteisele** [EgonOlsen71/basicv2#57]
The compiler is able to work with PRG files, but console and basicshell have problems:

console: the program is loaded, but there is a syntax error shown when starting it
basicshell: there is a READY message when loading it, but there is no line shown with LIST.

PRG files have two advantages:
- there are lot of PRG files available, because it is the standard format
- with PRG files there are no probems with control codes in strings (e. g. CLS) and with  lowercase/uppercase

Therefore it were good when console and basicshell could load PRG files. Perhaps you can reuse code written for the compiler.

**Comment by EgonOlsen71** [comment]
Makes sense, I guess. I never thought about this use case, but I'll look into it...

**Comment by EgonOlsen71** [comment]
Please give it a try now.

**Comment by viteisele** [comment]
Good work :-)
I saw one little issue with PI:

Inside a string the character for PI is converted to chr$(255) by Commodore Basic.
In Commodore Basic  chr$(126) and chr$(255) are the same character, but no for console support.

**Comment by EgonOlsen71** [comment]
This whole PI thing is disaster. Who on earth had the idea to put this into Commodore BASIC? There's zero need for it and all it does is causing trouble and extra code even in the BASIC interpreter of the actual C64.
I'll see, if I can improve this...

**Comment by EgonOlsen71** [comment]
Please try again...

**Comment by viteisele** [comment]
PI is now also working with PRG files :-)
