### ISSUE TITLE
BasicShell: no run with linenumber

### ISSUE THREAD

**Issue by viteisele** [EgonOlsen71/basicv2#60]
When with Basicrun a program should be started at a specific line, there is an error:

![image](https://github.com/EgonOlsen71/basicv2/assets/134144338/efa7ae87-5285-488a-b3c0-19fdfb4086a3)

It would be nice, when a run with linenumber would be possible as in the C64

**Comment by EgonOlsen71** [comment]
Might work now. It was a bit of a hack to support this, because the interpreter actually doesn't really support starting the program at any line but at the start. I hope this has to side effects...

**Comment by EgonOlsen71** [comment]
Note: When giving it a non-existing line, it won't error out but simply start at the first line instead.

**Comment by viteisele** [comment]
Maybe the hack doesn't work:
![image](https://github.com/EgonOlsen71/basicv2/assets/134144338/4d0e1d3f-98f0-401a-830b-3b6774ad7efc)

And the help text should be updated to "run [number]"

**Comment by EgonOlsen71** [comment]
I see. I guess the hack is actually fine, but the behaviour of RUN in the interpreter itself wasn't quite what one would expect.

Please give it another try.

**Comment by viteisele** [comment]
Much better now :-) Now it works as described
When you have time you should improve the text in the helpwindow
