### ISSUE TITLE
Error compiling: Failed to run optimizer!

### ISSUE THREAD

**Issue by sine707** [EgonOlsen71/basicv2#61]
I get the following error when trying to compile:
```
!!! Error compiling: Failed to run optimizer!
*Error at: 10130 data  315,890,0,-1,0,0,-1,0
Caused by: java.lang.IllegalArgumentException: fromIndex(467) > toIndex(335)
```
Running on latest master.

**Comment by EgonOlsen71** [comment]
That's most likely not the line that causes this but simply the last line in the program. Can you provide me with the complete source code, so that I can see for myself!?

**Comment by EgonOlsen71** [comment]
Might be fixed now...please give it a try...

**Comment by sine707** [comment]
Tried it, works now! :)
